### ISSUE TITLE
Webapp seem broken ?

### ISSUE THREAD

**Issue by Carreau** [scientific-python/repo-review#208]
Using the example of scikit-hep/hist 

https://scientific-python.github.io/repo-review/?repo=scikit-hep%2Fhist&branch=main

I get

```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 5, in 
  File "", line 7, in __init__
  File "/lib/python3.11/site-packages/repo_review/ghpath.py", line 59, in __post_init__
    val: io.StringIO = self.open_url(url)
                       ^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/repo_review/ghpath.py", line 53, in open_url
    with urllib.request.urlopen(url) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/lib/python311.zip/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: 
```

Edit: works from the CLI, so unsure.

**Comment by henryiii** [comment]
Same is happening here: https://scientific-python.github.io/repo-review/?repo=scikit-hep%2Fhist&branch=main - not sure what changed, but it's not picking up the injection of open_url. The next version modifies this a bit, but that's not out yet, so no idea why it's broken yet.

**Comment by henryiii** [comment]
Actually, I understand why the local demo is broken - it expects the unreleased version of repo-review. Ahh, your link is the unreleased version too! That's why. I thought you were pointing at the dev guide. Probably should just make a release, then.

**Comment by henryiii** [comment]
0.11 is out which fixes this.

**Comment by Carreau** [comment]
Ah, sorry ! thanks for the quick fix !
